project:
  type: book
  output-dir: _book

book:
  title: "Quarto Template"
  author: "SACA Group"
  chapters:
    - index.qmd
    - 02-Part2.qmd
    - 03-Part3.qmd
    - 04-Part4.qmd
  downloads: [pdf]
  

language:
  labels:
    chapter: "Part "

execute:
  freeze: auto

bibliography: [book.bib, packages.bib]


format:
  html:
    css: style.css
    toc: true
    margin-header: |
      ![](/logos/UoNTransparent.png)
    theme:
      light: theme/light.scss
      dark: theme/dark.scss
    
  pdf:
    toc: true
    shift-heading-level-by: 1
    number-sections: true
    number-depth: 3
    documentclass: article
    include-in-header: preamble.tex
    pdf-engine: pdflatex
    citation-package: natbib
    keep-tex: true

