---
title: "R Bookdown Template "
author: "Lisa Mott & Tom Wicks"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
   # pandoc_args: ["--number-offset=6"] Optional I want the chapters to be week 7, week 8 etc.
    config:
      sharing: false
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: true
description: "This is the notes for your_module_name"
---


# Introduction to R Bookdown

This is a template to create notes in R bookdown. For more information on R bookdown please see [this website.](https://bookdown.org/yihui/bookdown/?target=_blank)

## R Bookdown Installation

::: note
If you do not already have R and RStudio installed on your computer, go to the [RStudio Desktop download page](https://posit.co/download/rstudio-desktop/?target=_blank) and follow the instructions to install (1) R and (2) RStudio.
:::

### Use RStudio to install R Bookdown {-}

Open RStudio. In the console (box on the left-hand side in the default view), type

``` {r eval=FALSE}
install.packages("bookdown")
```

## Compile a Book
Follow the steps below to download and compile the source code for this template in R Bookdown.

1) Go to the [Accessible Maths Materials Sharepoint](https://uniofnottm.sharepoint.com/sites/AccessibleMathsMaterials?target=_blank) and click on the **Download Source Files** link under R Bookdown to download `BookdownExample.zip`.
2) Move the file to the folder where you want to store your notes, then unzip it to the same folder.

:::tip
Instructions for unzipping files: [[Windows](https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc?target=_blank), [MacOS](https://support.apple.com/en-gb/guide/mac-help/mchlp2528/mac#:~:text=Unzip%20(expand)%20a%20compressed%20item,zip%20file.?target=_blank), [Linux](https://unstop.com/blog/how-to-unzip-a-file-in-linux?target=_blank)]
:::

3) In RStudio in the top-right corner click on the blue Project sign. Click on "Open Project" and navigate to your unzipped file, then open `r_bookdown_template.Rproj`.

4) In the box with "Environment", "History", "Connections", "Build", "Tutorial", click on the "Build" tab, then click on the "Build Book" button.

5) On clicking the button in the previous step, a preview of your compiled book should appear. To view your book outside of RStudio, navigate to the "_book" subfolder that was created when you compiled your book, then open `index.html` in your favourite browser.

## Upload Your Book to Moodle
Please watch the video guide below.

If the link does not work then [please click here.](https://mediaspace.nottingham.ac.uk/media/How+to+upload+R+bookdown+file+to+Moodle/1_la5eitil)

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1355621/sp/135562100/embedIframeJs/uiconf_id/13188771/partner_id/1355621?iframeembed=true&playerId=kaltura_player&entry_id=1_la5eitil&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;" width="456" height="292" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>

Please watch the video guide below.

If the link does not work then [please click here.](https://mediaspace.nottingham.ac.uk/media/Clip+of+How+to+upload+R+Bookdown+html+to+Moodle/1_9hm74lrs)

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1355621/sp/135562100/embedIframeJs/uiconf_id/13188771/partner_id/1355621?iframeembed=true&playerId=kaltura_player&entry_id=1_9hm74lrs&flashvars[streamerType]=auto&amp;flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_0ysdz76w" width="456" height="292" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Clip of How to upload R Bookdown html to Moodle"></iframe>
